# Generated by Django 5.2.9 on 2026-02-23 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(help_text='OpenBIS space name', max_length=255)),
                ('project_name', models.CharField(blank=True, help_text='OpenBIS project name (optional)', max_length=255)),
                ('collection_name', models.CharField(blank=True, help_text='OpenBIS collection/experiment name (optional)', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the upload session', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing was completed', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if status is FAILED')),
                ('user', models.ForeignKey(help_text='User who initiated this upload session', on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Session',
                'verbose_name_plural': 'Upload Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Celery task UUID', max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('PROCESS_FILES', 'Process Files'), ('CLEANUP_FILES', 'Cleanup Files')], help_text='Type of task', max_length=20)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current Celery task state', max_length=20)),
                ('progress_current', models.IntegerField(default=0, help_text='Current progress (0-100)')),
                ('progress_total', models.IntegerField(default=100, help_text='Total progress units')),
                ('progress_status', models.CharField(blank=True, default='', help_text='Human-readable progress status', max_length=255)),
                ('result', models.JSONField(blank=True, help_text='Task result (success data)', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if state is FAILURE')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this task was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed', null=True)),
                ('upload_session', models.ForeignKey(help_text='Upload session this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.uploadsession')),
            ],
            options={
                'verbose_name': 'Upload Task',
                'verbose_name_plural': 'Upload Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['user', '-created_at'], name='app_uploads_user_id_7d4d41_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['status'], name='app_uploads_status_07ad0f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadtask',
            index=models.Index(fields=['upload_session', 'task_type'], name='app_uploadt_upload__818905_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadtask',
            index=models.Index(fields=['state'], name='app_uploadt_state_63c609_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadtask',
            index=models.Index(fields=['task_id'], name='app_uploadt_task_id_93898a_idx'),
        ),
    ]
