# Generated by Django 5.2.9 on 2026-02-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='uploadsession',
            name='app_uploads_user_id_7d4d41_idx',
        ),
        migrations.RemoveField(
            model_name='uploadsession',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='openbis_username',
            field=models.CharField(default='UnknownUser', help_text='OpenBIS username who initiated this upload session', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['openbis_username', '-created_at'], name='app_uploads_openbis_9f8ea0_idx'),
        ),
    ]
